pool.size=20

clean-schedule=0 2 15 * * 1-5
update-minute=0 * * * * 1-5

start-schedule1=0 30 20 * * 1-5
start-schedule2=0 55 8 * * 1-5
start-schedule3=0 25 10 * * 1-5
start-schedule4=0 25 13 * * 1-5

end-schedule1=0 01 23 * * 1-5
end-schedule2=0 16 10 * * 1-5
end-schedule3=0 31 11 * * 1-5
end-schedule4=0 2 15 * * 1-5

end-schedule5=0 30 16 * * 1-5
top-deal-close=0 31 16 * * 1-5
top-deal-close2=0 39 16 * * 1-5

update-15-night=0 1 23 * * 1-5
update-15-afternoon=0 31 11 * * 1-5
summary-night=0 2 23 * * 1-5
summary-afternoon=0 32 11 * * 1-5
night-middle=40 1 22 * * 1-5
early-morning=40 1 10 * * 1-5
half-morning=40 31 10 * * 1-5
early-afternoon=40 1 14 * * 1-5
before-close=40 46 14 * * 1-5
