server:
   port: 7700

spring:
   cloud:
      config:
         server:
            git:
               uri: https://github.com/hexin1250/application-config
               skipSslValidation: true
               timeout: 4
               force-pull: true
   application:
      name: config
